# Generated by Django 2.0.5 on 2018-06-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='barber_name',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
